Repository GideokKim/google-python-style-guide-kr, pull requests merged in 2025-03, with the labels that each got.

#87 docs: add hidden mission
  README.md
Labels: documentation, enhancement

#88 docs: add speed runner contributor
  README.md
Labels: documentation

#106 Update lgtm-approve.yml
  .github/workflows/lgtm-approve.yml
Labels: bug

#112 docs: update `CONTRIBUTING.md`
  CONTRIBUTING.md
Labels: documentation

#113 build: restrict target repository
  .github/workflows/gh-pages.yml
Labels: bug

#117 docs: update hidden mission
  README.md
Labels: documentation

#120 📝 fix: mkdocs에서 github alert 구문을 옳게 표시하도록 수정
  mkdocs.yml
  requirements.txt
Labels: documentation

#122 Docs/add special contributors
  README.md
Labels: documentation

#119 [3.19.13 Conditional Imports] 번역 추가
  google python style guide/Conditional Imports.md
  mkdocs.yml
Labels: documentation

#121 docs: README.md 업데이트 및 참가자 가이드 추가
  PARTICIPATION_GUIDE.md
  README.md
Labels: documentation
